theme: osuny
paginate: 18
enableRobotsTXT: true
removePathAccents: true
params:
  breadcrumb:
    position: hero-end
  summary:
    position: hero
  search:
    active: true
  debug:
     productionUrl: "https://www.rebootcommunication.org/"